apiVersion: v1
kind: Service
metadata:
  name: hr-assistant-service
spec:
  selector:
    app: hr-assistant
  ports:
  - name: streamlit
    port: 8501
    targetPort: 8501
  - name: api
    port: 8000
    targetPort: 8000
  type: LoadBalancer